# Generated by Django 5.2.8 on 2025-11-20 19:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(db_column='transaction_id_pk', primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='transaction_value', decimal_places=2, default=0.0, max_digits=10)),
                ('type', models.CharField(choices=[('REV', 'Revenue'), ('SPE', 'Spent')], db_column='transaction_type', max_length=3)),
                ('date', models.DateField(db_column='transaction_date', default=datetime.datetime.now)),
                ('description', models.TextField(db_column='transaction_description', null=True)),
                ('category', models.CharField(choices=[('INC_SALARY', 'Salary'), ('INC_INVESTMENT', 'Investment'), ('INC_FREELANCE', 'Freelance'), ('INC_DONATION', 'Donation'), ('INC_OTHER', 'Other Income'), ('EXP_FOOD', 'Food'), ('EXP_TRANSPORT', 'Transport'), ('EXP_ENTERTAINMENT', 'Entertainment'), ('EXP_INVOICE', 'Invoice'), ('EXP_OTHER', 'Other Expense')], db_column='transaction_category', max_length=20)),
                ('user', models.ForeignKey(db_column='transaction_user_id_fk', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'tbTransaction',
            },
        ),
    ]
