# Generated by Django 5.2.8 on 2025-11-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='user_id_pk', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='user_fullname', max_length=255)),
                ('email', models.EmailField(db_column='user_email', max_length=254, unique=True)),
                ('cpf', models.CharField(db_column='user_cpf', max_length=11, unique=True)),
                ('tel', models.CharField(db_column='user_tel', max_length=13, unique=True)),
            ],
            options={
                'db_table': 'tbUser',
            },
        ),
    ]
