---
config:
  theme: redux-dark-color
---
erDiagram
    Transaction {
        int id "PRIMARY KEY"
        string type "ENUM('EXPENSES','REVENUE')"
        float value "DECIMAL(10,2)"
        date date "DATE"
        string category_expenses "ENUM('salary','investments','freelance','gifts','others')"
        string category_revenue "ENUM('food','transportation','entertainment','utilities','others')"
        string description "TEXT"
        int user_id "FOREIGN KEY -> User.id"
    }

    User {
        int id "PRIMARY KEY"
        string key "VARCHAR(100)"
        string value "TEXT"
    }

    Goal {
        int id "PRIMARY KEY"
        string title "VARCHAR(255)"
        float value "DECIMAL(10,2)"
        string description "TEXT"
        date end_date "DATE"
        string status "ENUM('IN_PROGRESS','CANCELED','FINISHED','LOST')"
        int user_id "FOREIGN KEY -> User.id"
    }