---
config:
  theme: redux-dark-color
---
erDiagram
    Transaction {
        int transaction_id_pk "PRIMARY KEY"
        string transaction_user_id_fk "VARCHAR(100)"
        float transaction_value "DECIMAL(10,2)"
        string transaction_type "ENUM('EXPENSES','REVENUE')"
        date transaction_date "DATE"
        string transaction_description "TEXT"
        string transaction_category "ENUM('salary','investments','freelance','gifts','food','transportation','entertainment','utilities','others')"
        int user_id "FOREIGN KEY -> User.user_id_pk"
    }

    User {
        int user_id_pk "PRIMARY KEY"
        string user_fullname "VARCHAR(100)"
        string user_password "TEXT"
        string user_email "VARCHAR(254)"
        string user_cpf "VARCHAR(100)"
        string user_tel "VARCHAR(100)"
    }

    Goal {
        int goal_id "PRIMARY KEY"
        string goal_user_id_fk "VARCHAR(100)"
        string goal_title "VARCHAR(255)"
        float goal_value "DECIMAL(10,2)"
        string goal_description "TEXT"
        date goal_end_date "DATE"
        string goal_status "ENUM('IN_PROGRESS','CANCELED','FINISHED','LOST')"
        int user_id "FOREIGN KEY -> User.user_id_pk"
    }