---
config:
  look: handDrawn
  theme: redux-dark
---
classDiagram
    class Transaction {
        + id
        + type
        + value
        + date
        + category
        + description
    }
    class User {
        + name
        + email
        + phone
        + cpf
    }
    class Goal {
        + id
        + title
        + value
        + description
        + end_date
        + status
    }
