---
config:
  look: handDrawn
  theme: redux-dark
---
classDiagram
    class Transaction {
        + id
        + user
        + value
        + type
        + date
        + description
        + category
    }
    class User {
        + id
        + fullname
        + password
        + email
        + cpf
        + tel
    }
    class Goal {
        + id
        + user
        + title
        + value
        + description
        + end_date
        + status
    }
