# Generated by Django 5.2.8 on 2025-11-17 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(db_column='goal_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='goal_title', max_length=255, unique=True)),
                ('value', models.DecimalField(db_column='goal_value', decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(db_column='goal_description', null=True)),
                ('end_date', models.DateField(db_column='goal_end_date')),
                ('status', models.CharField(choices=[('IN_P', 'In Progress'), ('FINI', 'Finished'), ('FAIL', 'Failed'), ('CANC', 'Canceled')], db_column='goal_status', default='IN_P', max_length=4)),
                ('user', models.ForeignKey(db_column='goal_user_id_fk', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'tbGoal',
            },
        ),
    ]
